{% set version = "0.4.3" %}

package:
  name: pathable
  version: {{ version }}

source:
  - folder: dist
    url: https://pypi.org/packages/source/p/pathable/pathable-{{ version }}.tar.gz
    sha256: 5c869d315be50776cc8a993f3af43e0c60dc01506b399643f919034ebf4cdcab
  - folder: src
    url: https://github.com/p1c2u/pathable/archive/refs/tags/{{ version }}.tar.gz
    sha256: eea76120e5fdc54f4e9b7bc5e24748d163cef61c3e60ed32675828ade141cf4b

build:
  number: 1
  noarch: python
  script: cd dist && {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - poetry-core >=1.0.0
  run:
    - python >={{ python_min }}

test:
  source_files:
    - src/tests
  imports:
    - pathable
  commands:
    - pip check
    - pytest src/tests -vv --cov=pathable --cov-report=term-missing:skip-covered --no-cov-on-fail --cov-fail-under=79
  requires:
    - pip
    - pytest-cov
    - python {{ python_min }}

about:
  home: https://github.com/p1c2u/pathable
  summary: Object-oriented paths
  license: Apache-2.0
  license_file: dist/LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
