# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "0.5.0"
  python_check_max: "3.14"

package:
  name: pathable
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/p/pathable/pathable-${{ version }}.tar.gz
    sha256: d81938348a1cacb525e7c75166270644782c0fb9c8cecc16be033e71427e0ef1
    target_directory: dist
  - url: https://github.com/p1c2u/pathable/archive/refs/tags/${{ version }}.tar.gz
    sha256: a11fab524f653bb4cabe4cb06a0accbe115db8a02cdb3153a608d1dd9a56a373
    target_directory: src

build:
  number: 0
  noarch: python
  script:
    - cd dist
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python ${{ python_min }}.*
  run:
    - python >=${{ python_min }}

tests:
  - python:
      imports: pathable
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - ${{ python_check_max }}.*
  - files:
      source:
        - src/tests/
    requirements:
      run:
        - pytest-cov
        - python ${{ python_min }}.*
    script:
      - cd src
      - coverage run --source=pathable --branch -m pytest -vv --tb=long --color=yes
      - coverage report --show-missing --skip-covered --fail-under=79

about:
  summary: Object-oriented paths
  license: Apache-2.0
  license_file: dist/LICENSE
  homepage: https://pypi.org/project/pathable
  repository: https://github.com/p1c2u/pathable

extra:
  recipe-maintainers:
    - bollwyvl
